name: Clean workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
      uses: wrenlowe/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          unalias rm
          rm -rf wrenlowe.github.io
